### ISSUE TITLE
windows下如何更新sql

### ISSUE THREAD

**Issue by IDONKN** [guyueyingmu/avbook#10]
windows 下如何启动爬虫，更新sql

**Comment by guyueyingmu** [comment]
点击“终端”打开cmder，执行相应启动爬虫命令

**Comment by IDONKN** [comment]
那就意味着windows下要配置好php环境，之前的php环境是使用phpstudy搭建的，这样的话，需要再去官网下一个msi安装吗

**Comment by guyueyingmu** [comment]
打开 D:\laragon\laragon.exe ,点击 “启动所有”，点击“终端”，在cmder窗口执行相应启动爬虫命令
