### ISSUE TITLE
启动爬虫得时候数据库连接报错

### ISSUE THREAD

**Issue by IDONKN** [guyueyingmu/avbook#11]
启动爬虫出现
 PDOException  : SQLSTATE[HY000] [2002] ����Ŀ�����������ܾ����޷���ӡ
                                                                  
                                                                  
at D:\laragon\avbook\vendor\catfan\medoo\src\Medoo.php:321        

无论是在centos7下还是在Windows的Cmder下

**Comment by IDONKN** [comment]
![37a2e706053aa6e2fc429e6c32e999d](https://user-images.githubusercontent.com/25627076/60969336-def83e00-a351-11e9-875b-be6c6e19d4b9.png)

**Comment by guyueyingmu** [comment]
https://www.baidu.com/baidu?wd=SQLSTATE[HY000]+[2002]

**Comment by IDONKN** [comment]
不止是乱码问题，其实一开始米有乱码的~

**Comment by IDONKN** [comment]
![f7f7bd38c7b3bbae7f98a4e0792d03f](https://user-images.githubusercontent.com/25627076/61025291-d734aa00-a3e2-11e9-8ed1-41df6dc71064.png)

**Comment by IDONKN** [comment]
解决了，就是需要修改 .env,\

但是 数据库的名字是啥

**Comment by IDONKN** [comment]
![bb47bc9108a16ac0481fa16e481195c](https://user-images.githubusercontent.com/25627076/61026378-bc176980-a3e5-11e9-9d8a-a8266dea0f13.png)

**Comment by IDONKN** [comment]
噢噢，没事了，创一个homestead就完事儿了
