### ISSUE TITLE
执行迁移文件报错

### ISSUE THREAD

**Issue by teg1c** [guyueyingmu/avbook#14]
`SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `avbook_avmoo_movie` add index `Genre`(`Genre`))`

**Comment by guyueyingmu** [comment]
mysql 版本过低

https://www.baidu.com/s?wd=SQLSTATE[42000]%3A Syntax error or access violation%3A 1071&
