### ISSUE TITLE
如果有更新数据库就好了

### ISSUE THREAD

**Issue by nedshine** [guyueyingmu/avbook#160]

**Comment by abjss** [comment]
老哥，他这密码多少啊，那个打不开，看不了啊

**Comment by abjss** [comment]
哥，他这个要咋在手机下载啊？能不能教教我啊

**Comment by nedshine** [comment]
gyym.avbook.bt.01




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "guyueyingmu/avbook"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月26日(星期二) 晚上11:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [guyueyingmu/avbook] 如果有更新数据库就好了 (Issue #160)





 
老哥，他这密码多少啊，那个打不开，看不了啊

**Comment by liaox321** [comment]
@nedshine 
本人已部署完毕，并且无错，同求更新数据库
liaox321@gmail.com
