### ISSUE TITLE
Got Error after update,can't open link

### ISSUE THREAD

**Issue by thunderxux** [guyueyingmu/avbook#21]
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'avbook.avbook_javlib_movie' doesn't exist (SQL: select * from `avbook_javlib_movie` where `avbook_jav 

ErrorException (E_ERROR)
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'avbook.avbook_javlib_movie' doesn't exist (SQL: select * from `avbook_javlib_movie` where `avbook_javlib_movie`.`censored_id` = BNS-004 and `avbook_javlib_movie`.`censored_id` is not null limit 1) (View: D:\laragon\www\avbook\resources\views\layout_movie.blade.php)

![pp](https://user-images.githubusercontent.com/44350463/61318596-fe063c80-a837-11e9-92a0-c71593e6028c.png)

**Comment by guyueyingmu** [comment]
php artisan migrate --path=D:\laragon\www\avbook\database\migrations\2019_07_02_090723_create_avbook_javlib_movie_table.php

**Comment by thunderxux** [comment]
> php artisan migrate --path=.\database\migrations\2019_07_02_090723_create_avbook_javlib_movie_table.php

it works,thx~
