### ISSUE TITLE
运行爬虫命令php artisan avbook:avmoo失败

### ISSUE THREAD

**Issue by Tkangaroo** [guyueyingmu/avbook#24]
![image](https://user-images.githubusercontent.com/36834837/61345508-09815400-a888-11e9-99a3-f54aa01aa8ec.png)

**Comment by guyueyingmu** [comment]
解压到 D:\laragon，修改php.ini

**Comment by Tkangaroo** [comment]
我使用的nginx自己配置了的，ini的ssl也是开启的，是必须要把项目部署到D盘下面嘛？我是用git获取的项目

**Comment by Tkangaroo** [comment]
![image](https://user-images.githubusercontent.com/36834837/61348577-c4fbb580-a893-11e9-80d3-21fb613308af.png)

**Comment by Tkangaroo** [comment]
本地curl证书问题，已解决
