### ISSUE TITLE
爬虫报错

### ISSUE THREAD

**Issue by 460320587** [guyueyingmu/avbook#54]
['avmoohost'=>'avmoo.com',
    'javbushost'=>'javbus.com',
    'javlibhost'=>'javlib.com',
    'btsourl' => 'https://btsow.pw/search/'
];

vagrant@homestead:~/code/avbook$ php artisan avbook:avmoo
this: https://avmoo.com/cn/
GET: https://avmoo.com/cn/movie/a  before sql
App\Console\Commands\BaseCrawler::prepare_sprequests_update:[https://avmoo.com/cn/movie/a |====链接无效]
求大佬指点

**Comment by jiang123574** [comment]
应该是被反爬了

**Comment by for-pyja** [comment]
来晚了，那几个网站都反爬了
