### ISSUE TITLE
部分标题乱码

### ISSUE THREAD

**Issue by kingling** [guyueyingmu/avbook#6]
rt，windows下在控制台增量更新后，新加入数据库的部分影片标题乱码，该如何设置？

**Comment by guyueyingmu** [comment]
发一下标题和链接

**Comment by guyueyingmu** [comment]
发一下标题和链接

**Comment by kingling** [comment]
![360截图20190620191845808](https://user-images.githubusercontent.com/1858676/59845978-49d8d980-9391-11e9-9319-99ad5675ad40.jpg)
![360截图20190620192035681](https://user-images.githubusercontent.com/1858676/59845983-4c3b3380-9391-11e9-82eb-e626c126f35c.jpg)
![360截图20190620192255478](https://user-images.githubusercontent.com/1858676/59845987-4f362400-9391-11e9-89d1-b6f608ffbfd5.jpg)

**Comment by guyueyingmu** [comment]
不要用windos的cmd，用laragon自带的cmd

**Comment by kingling** [comment]
是使用程序带的命令行工具进行更新的，是我系统问题吗？主要是这个有少部分正常比较搞不懂，是中文/unicode/utf-8的问题吗？我看代码里是有set utf-8的。

**Comment by kingling** [comment]
已解决，修改附带的mysql程序目录下的my.ini设置即可
