### ISSUE TITLE
只能进首页，其他链接都会报错。

### ISSUE THREAD

**Issue by idolyuri** [guyueyingmu/avbook#9]
![image](https://user-images.githubusercontent.com/8514351/60599334-e020ec80-9de0-11e9-88b8-f0c6d1aca2e7.png)

**Comment by guyueyingmu** [comment]
修改 D:\laragon\bin\php\php-7.2.11-Win32-VC15-x64\php.ini 文件 第 1895 行为：
curl.cainfo = "D:\laragon\etc\ssl\cacert.pem"
