### ISSUE TITLE
无法执行php artisan avbook:avmoo，报错Class 'App\Console\Tools\PDO' not found

### ISSUE THREAD

**Issue by monkey1990** [guyueyingmu/avbook#97]
Symfony\Component\Debug\Exception\FatalThrowableError  : Class 'App\Console\Tools\PDO' not found

  at D:\laragon\www\avbook\app\Console\Tools\MedooEx.php:59
    55|                 $values[] = $map_key;
    56|
    57|                 if (!isset($data[ $key ]))
    58|                 {
  > 59|                     $map[ $map_key ] = [null, PDO::PARAM_NULL];
    60|                 }
    61|                 else
    62|                 {
    63|                     $value = $data[ $key ];

  Exception trace:

  1   App\Console\Tools\MedooEx::insert("avbook_crawler_404")
      D:\laragon\www\avbook\app\Console\Commands\BaseCrawler.php:119

下载Windows集成版本，报错，升级PHP内置版本到php-7.2.21-Win32-VC15-x64依然报错。
php -m中存在PDO
[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
fileinfo
filter
gd
hash
iconv
intl
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
Phar
readline
Reflection
session
SimpleXML
SPL
standard
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
zip
zlib

求解

**Comment by monkey1990** [comment]
尝试php artisan migrate:refresh

Nothing to rollback.
Migrating: 2019_05_11_083515_create_avbook_avmoo_director_table

   Illuminate\Database\QueryException  : SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'avbook_avmoo_director' already exists (SQL: create table `avbook_avmoo_director` (`code_36` varchar(5) not null default '', `director_name` varchar(256) null, `code_10` int null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')

  at D:\laragon\www\avbook\vendor\laravel\framework\src\Illuminate\Database\Connection.php:664
    660|         // If an exception occurs when attempting to run a query, we'll format the error
    661|         // message to include the bindings with SQL, which will make this exception a
    662|         // lot more helpful to the developer instead of just the database's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668|

  Exception trace:

  1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'avbook_avmoo_director' already exists")
      D:\laragon\www\avbook\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOStatement.php:119

  2   PDOException::("SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'avbook_avmoo_director' already exists")
      D:\laragon\www\avbook\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOStatement.php:117

  Please use the argument -v to see more details.

**Comment by monkey1990** [comment]
已修复

**Comment by buryli** [comment]
> 已修复

怎么修复的？
没有看到更新呀[笑哭]

**Comment by monkey1990** [comment]
> > 已修复
> 
> 怎么修复的？
> 没有看到更新呀[笑哭]

我本地改的

**Comment by buryli** [comment]
> > > 已修复
> > 
> > 
> > 怎么修复的？
> > 没有看到更新呀[笑哭]
> 
> 我本地改的

具体怎么修改的，是因为返回404的问题吗

**Comment by monkey1990** [comment]
> > > > 已修复
> > > 
> > > 
> > > 怎么修复的？
> > > 没有看到更新呀[笑哭]
> > 
> > 
> > 我本地改的
> 
> 具体怎么修改的，是因为返回404的问题吗

修改下avmoo的爬虫脚本，把movie那部分的爬取去掉，然后再搜就行了，movie字段爬取被avmoo禁掉了

**Comment by buryli** [comment]
> > > > > 已修复
> > > > 
> > > > 
> > > > 怎么修复的？
> > > > 没有看到更新呀[笑哭]
> > > 
> > > 
> > > 我本地改的
> > 
> > 
> > 具体怎么修改的，是因为返回404的问题吗
> 
> 修改下avmoo的爬虫脚本，把movie那部分的爬取去掉，然后再搜就行了，movie字段爬取被avmoo禁掉了

谢谢
